
package ch06.sslWS.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoSSLService", targetNamespace = "http://sslWS.ch06/", wsdlLocation = "http://computer:8080/EchoSSLService/EchoSSL?wsdl")
public class EchoSSLService
    extends Service
{

    private final static URL ECHOSSLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECHOSSLSERVICE_EXCEPTION;
    private final static QName ECHOSSLSERVICE_QNAME = new QName("http://sslWS.ch06/", "EchoSSLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://computer:8080/EchoSSLService/EchoSSL?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOSSLSERVICE_WSDL_LOCATION = url;
        ECHOSSLSERVICE_EXCEPTION = e;
    }

    public EchoSSLService() {
        super(__getWsdlLocation(), ECHOSSLSERVICE_QNAME);
    }

    public EchoSSLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOSSLSERVICE_QNAME, features);
    }

    public EchoSSLService(URL wsdlLocation) {
        super(wsdlLocation, ECHOSSLSERVICE_QNAME);
    }

    public EchoSSLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOSSLSERVICE_QNAME, features);
    }

    public EchoSSLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoSSLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoSSL
     */
    @WebEndpoint(name = "EchoSSLPort")
    public EchoSSL getEchoSSLPort() {
        return super.getPort(new QName("http://sslWS.ch06/", "EchoSSLPort"), EchoSSL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoSSL
     */
    @WebEndpoint(name = "EchoSSLPort")
    public EchoSSL getEchoSSLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sslWS.ch06/", "EchoSSLPort"), EchoSSL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOSSLSERVICE_EXCEPTION!= null) {
            throw ECHOSSLSERVICE_EXCEPTION;
        }
        return ECHOSSLSERVICE_WSDL_LOCATION;
    }

}
