
package ch06.sslWS.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EchoSSL", targetNamespace = "http://sslWS.ch06/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoSSL {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://sslWS.ch06/", className = "ch06.sslWS.client.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://sslWS.ch06/", className = "ch06.sslWS.client.EchoResponse")
    @Action(input = "http://sslWS.ch06/EchoSSL/echoRequest", output = "http://sslWS.ch06/EchoSSL/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
